tradutor1 = {}
tradutor1 = {"pineapple" : "abacaxi", "apple" : "maça" , "oranje" : "laranla"}

print(tradutor1)
print(tradutor1["apple"])
del (tradutor1 ["apple"])
print(tradutor1)

tradutor1 = {}
tradutor1 = {"pineapple" : "abacaxi", "apple" : "maça" , "oranje" : "laranla"}
print("pineapple" in tradutor1)

print()

dados = {
    'Crossfox':{'km':3500, 'ano':2005},
    'DS5' :{'km':3500, 'ano':2015},
    'Fusca' :{'km':130000, 'ano':1979},
    'Jetta' :{'km':56000, 'ano':2011},
    'Passat' :{'km':62000, 'ano':1999},
}
print (dados ['Fusca']['ano'])
print(dados.get('jetta'))

print()
print('#############')
print()

# Dicionário inglês -> português (exemplo com poucas palavras)
dicionario_pt_en = {
    "apple": "maçã",
    "house": "casa",
    "car": "carro",
    "book": "livro",
    "dog": "cachorro",
    "cat": "gato",
    "water": "água",
    "computer": "computador",
    "phone": "telefone",
    "table": "mesa",
    "apple": "maçã",
    "house": "casa",
    "car": "carro",
    "book": "livro",
    "dog": "cachorro",
    "cat": "gato",
    "water": "água",
    "computer": "computador",
    "phone": "telefone",
    "table": "mesa",
    "chair": "cadeira",
    "tree": "árvore",
    "sun": "sol",
    "moon": "lua",
    "star": "estrela",
    "boy": "menino",
    "girl": "menina",
    "man": "homem",
    "woman": "mulher",
    "child": "criança",
    "window": "janela",
    "door": "porta",
    "pen": "caneta",
    "pencil": "lápis",
    "paper": "papel",
    "notebook": "caderno",
    "school": "escola",
    "teacher": "professor",
    "student": "aluno",
    "blackboard": "quadro",
    "bottle": "garrafa",
    "glass": "copo",
    "milk": "leite",
    "bread": "pão",
    "cheese": "queijo",
    "butter": "manteiga",
    "coffee": "café",
    "tea": "chá",
    "juice": "suco",
    "egg": "ovo",
    "meat": "carne",
    "fish": "peixe",
    "chicken": "frango",
    "rice": "arroz",
    "beans": "feijão",
    "soup": "sopa",
    "salt": "sal",
    "sugar": "açúcar",
    "pepper": "pimenta",
    "onion": "cebola",
    "garlic": "alho",
    "lettuce": "alface",
    "tomato": "tomate",
    "potato": "batata",
    "carrot": "cenoura",
    "cucumber": "pepino",
    "banana": "banana",
    "orange": "laranja",
    "grape": "uva",
    "pineapple": "abacaxi",
    "strawberry": "morango",
    "lemon": "limão",
    "peach": "pêssego",
    "watermelon": "melancia",
    "mango": "manga",
    "airport": "aeroporto",
    "bus": "ônibus",
    "train": "trem",
    "station": "estação",
    "street": "rua",
    "road": "estrada",
    "bridge": "ponte",
    "hotel": "hotel",
    "restaurant": "restaurante",
    "market": "mercado",
    "store": "loja",
    "shop": "loja",
    "bank": "banco",
    "hospital": "hospital",
    "pharmacy": "farmácia",
    "church": "igreja",
    "university": "universidade",
    "library": "biblioteca",
    "cinema": "cinema",
    "theater": "teatro",
    "museum": "museu",
    "park": "parque",
    "zoo": "zoológico",
    "pool": "piscina",
    "sea": "mar",
    "river": "rio",
    "lake": "lago",
    "mountain": "montanha",
    "forest": "floresta",
    "desert": "deserto",
    "island": "ilha",
    "beach": "praia",
    "valley": "vale",
    "volcano": "vulcão",
    "fire": "fogo",
    "earth": "terra",
    "air": "ar",
    "wind": "vento",
    "rain": "chuva",
    "snow": "neve",
    "storm": "tempestade",
    "cloud": "nuvem",
    "sky": "céu",
    "weather": "clima",
    "hot": "quente",
    "cold": "frio",
    "warm": "morno",
    "cool": "fresco",
    "day": "dia",
    "night": "noite",
    "morning": "manhã",
    "afternoon": "tarde",
    "evening": "anoitecer",
    "week": "semana",
    "month": "mês",
    "year": "ano",
    "today": "hoje",
    "tomorrow": "amanhã",
    "yesterday": "ontem",
    "time": "tempo",
    "hour": "hora",
    "minute": "minuto",
    "second": "segundo",
    "clock": "relógio",
    "calendar": "calendário",
    "family": "família",
    "mother": "mãe",
    "father": "pai",
    "sister": "irmã",
    "brother": "irmão",
    "aunt": "tia",
    "uncle": "tio",
    "cousin": "primo",
    "grandmother": "avó",
    "grandfather": "avô",
    "son": "filho",
    "daughter": "filha",
    "baby": "bebê",
    "friend": "amigo",
    "neighbor": "vizinho",
    "boss": "chefe",
    "worker": "trabalhador",
    "job": "emprego",
    "work": "trabalho",
    "money": "dinheiro",
    "salary": "salário",
    "price": "preço",
    "cost": "custo",
    "buy": "comprar",
    "sell": "vender",
    "pay": "pagar",
    "open": "abrir",
    "close": "fechar",
    "start": "começar",
    "finish": "terminar",
    "run": "correr",
    "walk": "andar",
    "drive": "dirigir",
    "ride": "cavalgar",
    "fly": "voar",
    "swim": "nadar",
    "sleep": "dormir",
    "wake": "acordar",
    "eat": "comer",
    "drink": "beber",
    "read": "ler",
    "write": "escrever",
    "speak": "falar",
    "listen": "ouvir",
    "hear": "escutar",
    "see": "ver",
    "watch": "assistir",
    "look": "olhar",
     "maçã": "apple",
    "casa": "house",
    "carro": "car",
    "livro": "book",
    "cachorro": "dog",
    "gato": "cat",
    "água": "water",
    "computador": "computer",
    "telefone": "phone",
    "mesa": "table",
    "cadeira": "chair",
    "árvore": "tree",
    "sol": "sun",
    "lua": "moon",
    "estrela": "star",
    "menino": "boy",
    "menina": "girl",
    "homem": "man",
    "mulher": "woman",
    "criança": "child",
    "janela": "window",
    "porta": "door",
    "caneta": "pen",
    "lápis": "pencil",
    "papel": "paper",
    "caderno": "notebook",
    "escola": "school",
    "professor": "teacher",
    "aluno": "student",
    "quadro": "blackboard",
    "garrafa": "bottle",
    "copo": "glass",
    "leite": "milk",
    "pão": "bread",
    "queijo": "cheese",
    "manteiga": "butter",
    "café": "coffee",
    "chá": "tea",
    "suco": "juice",
    "ovo": "egg",
    "carne": "meat",
    "peixe": "fish",
    "frango": "chicken",
    "arroz": "rice",
    "feijão": "beans",
    "sopa": "soup",
    "sal": "salt",
    "açúcar": "sugar",
    "pimenta": "pepper",
    "cebola": "onion",
    "alho": "garlic",
    "alface": "lettuce",
    "tomate": "tomato",
    "batata": "potato",
    "cenoura": "carrot",
    "pepino": "cucumber",
    "banana": "banana",
    "laranja": "orange",
    "uva": "grape",
    "abacaxi": "pineapple",
    "morango": "strawberry",
    "limão": "lemon",
    "pêssego": "peach",
    "melancia": "watermelon",
    "manga": "mango",
    "aeroporto": "airport",
    "ônibus": "bus",
    "trem": "train",
    "estação": "station",
    "rua": "street",
    "estrada": "road",
    "ponte": "bridge",
    "hotel": "hotel",
    "restaurante": "restaurant",
    "mercado": "market",
    "loja": "shop",
    "banco": "bank",
    "hospital": "hospital",
    "farmácia": "pharmacy",
    "igreja": "church",
    "universidade": "university",
    "biblioteca": "library",
    "cinema": "cinema",
    "teatro": "theater",
    "museu": "museum",
    "parque": "park",
    "zoológico": "zoo",
    "piscina": "pool",
    "mar": "sea",
    "rio": "river",
    "lago": "lake",
    "montanha": "mountain",
    "floresta": "forest",
    "deserto": "desert",
    "ilha": "island",
    "praia": "beach",
    "vale": "valley",
    "vulcão": "volcano",
    "fogo": "fire",
    "terra": "earth",
    "ar": "air",
    "vento": "wind",
    "chuva": "rain",
    "neve": "snow",
    "tempestade": "storm",
    "nuvem": "cloud",
    "céu": "sky",
    "clima": "weather",
    "quente": "hot",
    "frio": "cold",
    "morno": "warm",
    "fresco": "cool",
    "dia": "day",
    "noite": "night",
    "manhã": "morning",
    "tarde": "afternoon",
    "anoitecer": "evening",
    "semana": "week",
    "mês": "month",
    "ano": "year",
    "hoje": "today",
    "amanhã": "tomorrow",
    "ontem": "yesterday",
    "tempo": "time",
    "hora": "hour",
    "minuto": "minute",
    "segundo": "second",
    "relógio": "clock",
    "calendário": "calendar",
    "família": "family",
    "mãe": "mother",
    "pai": "father",
    "irmã": "sister",
    "irmão": "brother",
    "tia": "aunt",
    "tio": "uncle",
    "primo": "cousin",
    "avó": "grandmother",
    "avô": "grandfather",
    "filho": "son",
    "filha": "daughter",
    "bebê": "baby",
    "amigo": "friend",
    "vizinho": "neighbor",
    "chefe": "boss",
    "trabalhador": "worker",
    "emprego": "job",
    "trabalho": "work",
    "dinheiro": "money",
    "salário": "salary",
    "preço": "price",
    "custo": "cost",
    "comprar": "buy",
    "vender": "sell",
    "pagar": "pay",
    "abrir": "open",
    "fechar": "close",
    "começar": "start",
    "terminar": "finish",
    "correr": "run",
    "andar": "walk",
    "dirigir": "drive",
    "cavalgar": "ride",
    "voar": "fly",
    "nadar": "swim",
    "dormir": "sleep",
    "acordar": "wake",
    "comer": "eat",
    "beber": "drink",
    "ler": "read",
    "escrever": "write",
    "falar": "speak",
    "ouvir": "listen",
    "escutar": "hear",
    "ver": "see",
    "assistir": "watch",
    "olhar": "look"


}

# Inverter o dicionário para inglês → português
dicionario_en_pt = {v: k for k, v in dicionario_pt_en.items()}

# Função para consultar tradução
def consultar():
    idioma = input("Qual idioma você está usando? (pt/en): ").strip().lower()
    palavra = input("Digite a palavra para traduzir: ").strip().lower()

    if idioma == "pt":
        traducao = dicionario_pt_en.get(palavra)
        if traducao:
            print(f"A tradução de '{palavra}' é '{traducao}'.")
        else:
            print("Palavra não encontrada.")
    elif idioma == "en":
        traducao = dicionario_en_pt.get(palavra)
        if traducao:
            print(f"The translation of '{palavra}' is '{traducao}'.")
        else:
            print("Word not found.")
    else:
        print("Idioma inválido. Use 'pt' para português ou 'en' para inglês.")

# Função para adicionar palavra
def adicionar():
    pt = input("Digite a palavra em português: ").strip().lower()
    en = input("Digite a tradução em inglês: ").strip().lower()
    if pt in dicionario_pt_en:
        print("Essa palavra já existe.")
    else:
        dicionario_pt_en[pt] = en
        dicionario_en_pt[en] = pt
        print("Palavra adicionada com sucesso!")

# Laço principal
while True:
    print("\nMenu de Tradução")
    print("1 - Consultar palavra")
    print("2 - Adicionar nova palavra")
    print("3 - Sair")
    opcao = input("Escolha uma opção: ")

    if opcao == "1":
        consultar()
    elif opcao == "2":
        adicionar()
    elif opcao == "3":
        print("Saindo do programa...")
        break
    else:
        print("Opção inválida. Tente novamente.")